In [1]:
%pylab inline
%load_ext autoreload
%autoreload 2
import numpy as np
from board_utils import *

Populating the interactive namespace from numpy and matplotlib


In [2]:
gen_board(3,3)

array([[6, 8, 2],
       [3, 7, 0],
       [5, 1, 4]])

In [3]:
target_array = np.array([[1,2,3],[8,0,4],[7,6,5]])

board = gen_board(3,3)
board

array([[5, 8, 7],
       [3, 2, 4],
       [0, 6, 1]])

In [4]:
target

array([[1, 2, 3],
       [8, 0, 4],
       [7, 6, 5]])

In [5]:
'''def within_range(i,j):
    return (i>-1 and i < 3 and j > -1 and j < 3)

def valid_neighbor(i,j, zero_x, zero_y):
    return (within_range(i,j) and (i!=zero_x and j!=zero_y))'''

'def within_range(i,j):\n    return (i>-1 and i < 3 and j > -1 and j < 3)\n\ndef valid_neighbor(i,j, zero_x, zero_y):\n    return (within_range(i,j) and (i!=zero_x and j!=zero_y))'

In [6]:
manhattan(board, target)

array([18])

In [7]:
get_valid_moves(board)

[[1, 0], [2, 1]]

In [8]:
board

array([[5, 8, 7],
       [3, 2, 4],
       [0, 6, 1]])

In [9]:
empty_x, empty_y = where(board, 0)
for n in get_valid_moves(board):
    x,y = n
    print(board[x,y])

3
6


In [10]:
empty = where(board, 0)
move = get_valid_moves(board)[0]
swap(empty, move, board)


array([[5, 8, 7],
       [0, 2, 4],
       [3, 6, 1]])

In [11]:
manhattan(board, target)

array([18])

In [12]:
b = Board(board, 0, target)
c = Board(board, 1, target)

In [13]:
fs = pathgen(c, target)

In [14]:
fs.sort(key=lambda x: x.f)

In [15]:
x = list(range(10))
x.sort()
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
Board(board, 0, target)

[[5 8 7]
 [3 2 4]
 [0 6 1]]

In [21]:
t = Board(target, 0, target)
t

[[1 2 3]
 [8 0 4]
 [7 6 5]]

In [18]:
t.is_target()

True

In [34]:
openList = []
closedList = []
# Add the start node:
#put the startNode on the openList (leave it's f at zero)
openList.append(b)
                                   
# Loop until you find the end
while len(openList) >  0:
    # Get the current node
    #let the currentNode equal the node with the least f value
    #remove the currentNode from the openList
    currNode = openList.sort(key=lambda x: x.f).pop(0)

    #add the currentNode to the closedList
    closedList.append(currNode)
    # Found the goal
    #if currentNode is the goal
    if currNode.is_target():
        #Congratz! You've found the end! Backtrack to get path
        print(currNode)
    # Generate children
    children = pathgen(b,t)    
    for child in children:
        # Child is on the closedList
        if child in closedList:
            continue 
        # Create the f, g, and h values - DONE BY BOARD OBJECT
        #child.g = currentNode.g + distance between child and current
        #child.h = distance from child to end
        #child.f = child.g + child.h

        # Child is already in openList
        if child in openList:
            if child.g > currNode.g:
                continue
        # Add the child to the openList
        openList.append(child)

AttributeError: 'NoneType' object has no attribute 'pop'